services:
  - type: web
    name: korean-vocab-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: GOOGLE_API_KEY
        sync: false  # 수동으로 설정 필요
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO